### ISSUE TITLE
BUG: Falta de validações no formulário de "Indicar centro Pokemon"

### ISSUE THREAD

**Issue by edumoreira1506** [pokemongovet/pokemongovet.github.io#91]
Fala pessoal!

Estava olhando e navegando pelo projeto, vi que a página "Indicar centro Pokemon" contém um formulário. Fiz alguns testes e vi que o formulário não possuia validação nenhuma... Importei duas dependências, uma é o sweetalert para informar o erro de validação ao usuário e outra é o jqueryMask para colocar máscara no campo de telefone.

Além disse, fiz algumas consultas na API de endereços do IBGE, agora quando o usuário insere o estado, ele precisa colocar uma UF que seja válida, depois disso, no envio do formulário, é também validado se a cidade que ele está enviando faz parte mesmo daquele estado.

Além disso o formulário agora está sendo enviado por ajax. São coisas simples, mas espero que gostem e eu possa ajudar mais futuramente :)

**Comment by fititnt** [comment]
Discussão no _pull request_ #92
